// This file is generated by Prismic local builder. Update with care!

export { default as Image } from './Image'
export { default as Meetings } from './Meetings'
export { default as Text } from './Text'
export { default as TextAndImage } from './TextAndImage'
export { default as Video } from './Video'
