// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Image from './Image';
import Meetings from './Meetings';
import Text from './Text';
import TextAndImage from './TextAndImage';
import Video from './Video';

export {
	ContactForm,
	Image,
	Meetings,
	Text,
	TextAndImage,
	Video,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	meetings: Meetings,
	text: Text,
	text_and_image: TextAndImage,
	video: Video,
};
