import { GetServerSideProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Client } from '../utils/prismicHelpers'
import {PrismicRichText, SliceZone, SliceZoneComponents} from "@prismicio/react";
import TextAndImage from '../slices/TextAndImage'
import {Homepage, SiteConfiguration} from "../utils/types";
import Meetings from "../slices/Meetings";

interface PageData {
    page: Homepage;
    config: SiteConfiguration;
}

export const getServerSideProps: GetServerSideProps<PageData> = async (context) => {
  const homepage = await Client().getSingle<Homepage>('homepage');
  const siteConfig = await Client().getSingle<SiteConfiguration>('site-configuration');

  return {
    props: {
        page: homepage,
        config: siteConfig
    },
  }
}

export default function Home( pageData: PageData ) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Scouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div id="content" className="pb-5">
              <div className="darkblue">
                  <div className="container py-8">
                      <div className="row d-flex align-items-center text-white">
                          <div className="col-12 col-sm-8 col-md-7 col-lg-6 col-xl-6">
                              <PrismicRichText field={pageData.page.data.title} />
                          </div>
                      </div>
                  </div>
              </div>

              <div className="container">
                  <SliceZone
                      slices={pageData.page.data.slices}
                      components={{
                          // @ts-ignore
                          text_and_image: TextAndImage,
                          // @ts-ignore
                          meetings: Meetings,
                      }}
                      context={pageData.config}
                  />
              </div>
          </div>
      </main>

    </div>
  )
}
