import { GetServerSideProps } from 'next'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Client } from '../utils/prismicHelpers'
import {PrismicDocumentWithUID, RichTextField} from "@prismicio/types";
import {PrismicRichText} from "@prismicio/react";


interface Homepage extends PrismicDocumentWithUID {
    type: "homepage";
    data: {
        title: RichTextField;
    }
}

interface HomepageDocument {
    document: Homepage;
}

export const getServerSideProps: GetServerSideProps<HomepageDocument> = async (context) => {
  const document = await Client().getSingle<Homepage>('homepage');

  return {
    props: {
      document
    },
  }
}

export default function Home( homepage: HomepageDocument ) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PrismicRichText field={homepage.document.data.title} />
      </main>

    </div>
  )
}
