import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Client } from '../utils/prismicHelpers'
import { RichText } from 'prismic-reactjs'


export const getServerSideProps: GetServerSideProps = async (context) => {
  const document = await Client().getSingle('homepage')

  return {
    props: {
      document
    },
  }
}

export default function Home( props ) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RichText render={props.document.data.title} />
      </main>

    </div>
  )
}
